routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::name('data.')->prefix('sipbas')->group(function(){
	Route::resource('divisi', 'DivisiController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('arsip', 'ArsipController');
});

Route::name('admin.')->prefix('private')->group(function(){
	Route::resource('users','UsersController');
	Route::patch('users/{id}/update/role','UsersController@changerole')->name('users.role.change');
	Route::resource('roles','RoleController');
});

resources/views/layouts/1/footer.blade.php
<!-- BEGIN: Footer-->
<footer class="page-footer footer footer-static footer-dark red gradient-shadow navbar-border navbar-shadow">
	<div class="footer-copyright">
		<div class="container"><span>&copy; 2020 <a>SIPBas</a> All rights reserved.</span><span class="right hide-on-small-only">Design and Developed by <a href="https://www.argiacyber.com/">ArgiaCyber</a></span></div>
	</div>
</footer>
<!-- END: Footer-->

resources/views/layouts/1/header.blade.php
<!-- BEGIN: Header-->
<header class="page-topbar" id="header">
	<div class="navbar navbar-fixed">
		<nav class="navbar-main navbar-color nav-collapsible sideNav-lock navbar-dark red">
			<div class="nav-wrapper">
				<ul class="navbar-list right">
					<li class="hide-on-med-and-down"><a class="waves-effect waves-block waves-light toggle-fullscreen" href="javascript:void(0);"><i class="material-icons">settings_overscan</i></a></li>
					<li><a class="waves-effect waves-block waves-light profile-button" href="javascript:void(0);" data-target="profile-dropdown"><span class="avatar-status avatar-online"><img src="{{ asset('images/avatar-7.png') }}" alt="avatar"><i></i></span></a></li>
				</ul>
				<!-- profile-dropdown-->
				<ul class="dropdown-content" id="profile-dropdown">
					<li class="divider"></li>
					<li><a class="grey-text text-darken-1" href="user-login.html"><i class="material-icons">keyboard_tab</i> Logout</a></li>
				</ul>
			</div>
		</nav>
	</div>
</header>
<!-- END: Header-->

resources/views/layouts/1/sidenav.blade.php
<!-- BEGIN: SideNav-->
<aside class="sidenav-main nav-expanded nav-lock nav-collapsible sidenav-dark red sidenav-active-rounded">
	<div class="brand-sidebar" style="background: #f44336">
		<h1 class="logo-wrapper">
			<a class="brand-logo red" href="index.html">
				{{-- <img class="hide-on-med-and-down " src="../../../app-assets/images/logo/materialize-logo.png" alt="materialize logo" />
				<img class="show-on-medium-and-down hide-on-med-and-up" src="../../../app-assets/images/logo/materialize-logo-color.png" alt="materialize logo" /> --}}
				<span class="logo-text hide-on-med-and-down">Arsip Bawaslu</span>
			</a>
			{{-- <a class="navbar-toggler" href="#">
				<i class="material-icons">radio_button_checked</i>
			</a> --}}
		</h1>
	</div>
	<ul class="sidenav sidenav-collapsible leftside-navigation collapsible sidenav-fixed menu-shadow" id="slide-out" data-menu="menu-navigation" data-collapsible="menu-accordion">
		<li class="navigation-header">
			<a class="navigation-header-text" style="color: #ffffff">Data Arsip</a>
			<i class="navigation-header-icon material-icons">more_horiz</i>
		</li>
		<li class="{{ (request()->is('sipbas/divisi*') ? 'active bold' : '') }}">
			<a class="waves-effect waves-cyan {{ (request()->is('sipbas/divisi*') ? 'active' : '') }}" href="{{ route('data.divisi.index') }}">
				<i class="material-icons">business</i>
				<span class="menu-title" data-i18n="Divisi">Divisi</span>
			</a>
		</li>
		<li class="{{ (request()->is('sipbas/kategori*') ? 'active bold' : '') }}">
			<a class="waves-effect waves-cyan {{ (request()->is('sipbas/kategori*') ? 'active' : '') }}" href="{{ route('data.kategori.index') }}">
				<i class="material-icons">call_split</i>
				<span class="menu-title" data-i18n="Kategori">Kategori</span>
			</a>
		</li>
		<li class="{{ (request()->is('sipbas/arsip*') ? 'active bold' : '') }}">
			<a class="waves-effect waves-cyan {{ (request()->is('sipbas/arsip*') ? 'active' : '') }}" href="{{ route('data.arsip.index') }}">
				<i class="material-icons">book</i>
				<span class="menu-title" data-i18n="Arsip">Arsip</span>
			</a>
		</li>

		<li class="navigation-header">
			<a class="navigation-header-text" style="color: #ffffff">Data User</a>
			<i class="navigation-header-icon material-icons">more_horiz</i>
		</li>
		<li class="{{ (request()->is('private/users*') ? 'active bold' : '') }}">
			<a class="waves-effect waves-cyan {{ (request()->is('private/users*') ? 'active' : '') }}" href="{{ route('admin.users.index') }}">
				<i class="material-icons">face</i>
				<span class="menu-title" data-i18n="Divisi">Users</span>
			</a>
		</li>
		<li class="{{ (request()->is('private/roles*') ? 'active bold' : '') }}">
			<a class="waves-effect waves-cyan {{ (request()->is('private/roles*') ? 'active' : '') }}" href="{{ route('admin.roles.index') }}">
				<i class="material-icons">accessibility</i>
				<span class="menu-title" data-i18n="Divisi">Roles</span>
			</a>
		</li>
	</ul>
</aside>
<!-- END: SideNav-->